# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255, unique=True)),
                ('load', models.TextField(max_length=1024)),
            ],
            options={
                'ordering': ('-jid',),
                'db_table': 'jids',
            },
        ),
        migrations.CreateModel(
            name='RestartJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(blank=True, max_length=128, null=True)),
                ('applitime', models.DateTimeField(auto_now=True)),
                ('projects', models.CharField(blank=True, max_length=128, null=True)),
                ('jenksins_job_name', models.CharField(blank=True, max_length=128, null=True)),
                ('jenksins_job_number', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=128, null=True)),
                ('restarttime', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-applitime'],
            },
        ),
        migrations.CreateModel(
            name='salt_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=1024)),
                ('alter_time', models.DateTimeField(auto_now_add=True)),
                ('master_id', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-id',),
                'db_table': 'salt_events',
            },
        ),
        migrations.CreateModel(
            name='salt_returns',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('fun', models.CharField(max_length=50)),
                ('jid', models.CharField(max_length=255)),
                ('return_char', models.TextField(db_column='return', max_length=1024)),
                ('id', models.CharField(max_length=50)),
                ('success', models.CharField(max_length=10)),
                ('full_ret', models.TextField(max_length=1024)),
                ('alter_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-custom_id',),
                'db_table': 'salt_returns',
            },
        ),
    ]
